<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <IsPackable>false</IsPackable>
    <RootNamespace>FloodLink.Tests</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\FloodLink.Domain\FloodLink.Domain.csproj" />
    <ProjectReference Include="..\..\src\FloodLink.Contracts\FloodLink.Contracts.csproj" />
    <ProjectReference Include="..\..\src\FloodLink.Api\FloodLink.Api.csproj" />
    <ProjectReference Include="..\..\src\FloodLink.Infrastructure\FloodLink.Infrastructure.csproj" />
    <ProjectReference Include="..\..\src\FloodLink.Agents.Routing\FloodLink.Agents.Routing.csproj" />
    <ProjectReference Include="..\..\src\FloodLink.Agents.Matching\FloodLink.Agents.Matching.csproj" />
    <ProjectReference Include="..\..\src\FloodLink.Agents.Validation\FloodLink.Agents.Validation.csproj" />
  </ItemGroup>


  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" />
    <PackageReference Include="Moq" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="coverlet.collector">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
    </PackageReference>
  </ItemGroup>
</Project>
