// <auto-generated />
using System;
using FloodLink.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FloodLink.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FloodLink.Domain.Entities.AgentExecutionLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AgentName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("DurationMs")
                        .HasColumnType("bigint");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text");

                    b.Property<string>("InputJson")
                        .HasColumnType("text");

                    b.Property<string>("OutputJson")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("ToolCallsJson")
                        .HasColumnType("text");

                    b.Property<Guid>("WorkflowRunId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("WorkflowRunId");

                    b.ToTable("AgentExecutionLogs");
                });

            modelBuilder.Entity("FloodLink.Domain.Entities.AllocationProposalEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DepotId")
                        .HasColumnType("integer");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<double>("Quantity")
                        .HasColumnType("double precision");

                    b.Property<int>("ShelterId")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("WorkflowRunId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("DepotId");

                    b.HasIndex("ShelterId");

                    b.HasIndex("WorkflowRunId");

                    b.ToTable("AllocationProposals", (string)null);
                });

            modelBuilder.Entity("FloodLink.Domain.Entities.Depot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.HasKey("Id");

                    b.ToTable("Depots");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 9, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            Latitude = 6.9271000000000003,
                            Longitude = 79.861199999999997,
                            Name = "Colombo Central Depot"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 9, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            Latitude = 6.9344000000000001,
                            Longitude = 79.984099999999998,
                            Name = "Kaduwela Supply Depot"
                        });
                });

            modelBuilder.Entity("FloodLink.Domain.Entities.InventoryItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DepotId")
                        .HasColumnType("integer");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<double>("QuantityAvailable")
                        .HasColumnType("double precision");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("DepotId", "ItemName")
                        .IsUnique();

                    b.ToTable("InventoryItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DepotId = 1,
                            ItemName = "Water",
                            QuantityAvailable = 600.0,
                            Unit = "bottles",
                            UpdatedAt = new DateTime(2026, 9, 25, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 2,
                            DepotId = 1,
                            ItemName = "Food",
                            QuantityAvailable = 250.0,
                            Unit = "packs",
                            UpdatedAt = new DateTime(2026, 9, 25, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 3,
                            DepotId = 2,
                            ItemName = "Water",
                            QuantityAvailable = 400.0,
                            Unit = "bottles",
                            UpdatedAt = new DateTime(2026, 9, 25, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 4,
                            DepotId = 2,
                            ItemName = "Medical",
                            QuantityAvailable = 50.0,
                            Unit = "kits",
                            UpdatedAt = new DateTime(2026, 9, 25, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("FloodLink.Domain.Entities.Report", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double?>("GpsLat")
                        .HasColumnType("double precision");

                    b.Property<double?>("GpsLng")
                        .HasColumnType("double precision");

                    b.Property<string>("NeedType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("PhotoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("QuantityNeeded")
                        .HasColumnType("integer");

                    b.Property<int>("ReportedBy")
                        .HasColumnType("integer");

                    b.Property<int>("ShelterId")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("UrgencyLevel")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ReportedBy");

                    b.HasIndex("ShelterId");

                    b.ToTable("Reports");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 9, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            GpsLat = 6.9271000000000003,
                            GpsLng = 79.861199999999997,
                            NeedType = "Water",
                            PhotoUrl = "https://storage.floodlink.lk/reports/photo_1.jpg",
                            QuantityNeeded = 500,
                            ReportedBy = 1,
                            ShelterId = 1,
                            Status = "New",
                            UrgencyLevel = 5
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 9, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            GpsLat = 6.9271000000000003,
                            GpsLng = 79.861199999999997,
                            NeedType = "Food",
                            PhotoUrl = "https://storage.floodlink.lk/reports/photo_2.jpg",
                            QuantityNeeded = 300,
                            ReportedBy = 1,
                            ShelterId = 1,
                            Status = "Triaged",
                            UrgencyLevel = 4
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 9, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            GpsLat = 6.9344000000000001,
                            GpsLng = 79.984099999999998,
                            NeedType = "Medical",
                            QuantityNeeded = 50,
                            ReportedBy = 2,
                            ShelterId = 2,
                            Status = "New",
                            UrgencyLevel = 5
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 9, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            GpsLat = 6.9344000000000001,
                            GpsLng = 79.984099999999998,
                            NeedType = "Shelter-Repair",
                            PhotoUrl = "https://storage.floodlink.lk/reports/photo_4.jpg",
                            QuantityNeeded = 20,
                            ReportedBy = 1,
                            ShelterId = 2,
                            Status = "InPlan",
                            UrgencyLevel = 3
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2026, 9, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            GpsLat = 7.0839999999999996,
                            GpsLng = 79.992500000000007,
                            NeedType = "Other",
                            QuantityNeeded = 100,
                            ReportedBy = 2,
                            ShelterId = 3,
                            Status = "Resolved",
                            UrgencyLevel = 2
                        });
                });

            modelBuilder.Entity("FloodLink.Domain.Entities.RouteEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DistanceMeters")
                        .HasColumnType("integer");

                    b.Property<int>("EstimatedDurationSeconds")
                        .HasColumnType("integer");

                    b.Property<string>("PolylineString")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("WorkflowRunId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("WorkflowRunId");

                    b.ToTable("Routes");
                });

            modelBuilder.Entity("FloodLink.Domain.Entities.Shelter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Capacity")
                        .HasColumnType("integer");

                    b.Property<int?>("ContactVolunteerId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CurrentOccupancy")
                        .HasColumnType("integer");

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ContactVolunteerId");

                    b.ToTable("Shelters");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Capacity = 200,
                            ContactVolunteerId = 1,
                            CreatedAt = new DateTime(2026, 9, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentOccupancy = 140,
                            Latitude = 6.9271000000000003,
                            Longitude = 79.861199999999997,
                            Name = "Central Colombo Relief Center",
                            Status = "Active",
                            UpdatedAt = new DateTime(2026, 9, 25, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 2,
                            Capacity = 150,
                            ContactVolunteerId = 1,
                            CreatedAt = new DateTime(2026, 9, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentOccupancy = 120,
                            Latitude = 6.9344000000000001,
                            Longitude = 79.984099999999998,
                            Name = "Kaduwela Community Hall",
                            Status = "Active",
                            UpdatedAt = new DateTime(2026, 9, 25, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 3,
                            Capacity = 100,
                            ContactVolunteerId = 2,
                            CreatedAt = new DateTime(2026, 9, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentOccupancy = 45,
                            Latitude = 7.0839999999999996,
                            Longitude = 79.992500000000007,
                            Name = "Gampaha Primary School Shelter",
                            Status = "Active",
                            UpdatedAt = new DateTime(2026, 9, 25, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("FloodLink.Domain.Entities.TriagePlanEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedByAgentRunId")
                        .HasColumnType("uuid");

                    b.PrimitiveCollection<string>("GeneratedFromReportIds")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("PlanSummaryJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<int>("PriorityRank")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByAgentRunId");

                    b.ToTable("TriagePlans", (string)null);
                });

            modelBuilder.Entity("FloodLink.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("HashedPassword")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 9, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            HashedPassword = "hashed_password_1",
                            Name = "John Doe",
                            Phone = "+94771234567",
                            Role = "Volunteer"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 9, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            HashedPassword = "hashed_password_2",
                            Name = "Jane Smith",
                            Phone = "+94779876543",
                            Role = "Coordinator"
                        });
                });

            modelBuilder.Entity("FloodLink.Domain.Entities.WorkflowRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CurrentState")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("FailedAtState")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Objective")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("PlanJson")
                        .HasColumnType("jsonb");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("WorkflowRuns");
                });

            modelBuilder.Entity("FloodLink.Domain.Entities.AgentExecutionLog", b =>
                {
                    b.HasOne("FloodLink.Domain.Entities.WorkflowRun", "WorkflowRun")
                        .WithMany()
                        .HasForeignKey("WorkflowRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WorkflowRun");
                });

            modelBuilder.Entity("FloodLink.Domain.Entities.AllocationProposalEntity", b =>
                {
                    b.HasOne("FloodLink.Domain.Entities.Depot", "Depot")
                        .WithMany()
                        .HasForeignKey("DepotId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FloodLink.Domain.Entities.Shelter", "Shelter")
                        .WithMany()
                        .HasForeignKey("ShelterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FloodLink.Domain.Entities.WorkflowRun", "WorkflowRun")
                        .WithMany()
                        .HasForeignKey("WorkflowRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Depot");

                    b.Navigation("Shelter");

                    b.Navigation("WorkflowRun");
                });

            modelBuilder.Entity("FloodLink.Domain.Entities.InventoryItem", b =>
                {
                    b.HasOne("FloodLink.Domain.Entities.Depot", "Depot")
                        .WithMany("InventoryItems")
                        .HasForeignKey("DepotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Depot");
                });

            modelBuilder.Entity("FloodLink.Domain.Entities.Report", b =>
                {
                    b.HasOne("FloodLink.Domain.Entities.User", "Reporter")
                        .WithMany("SubmittedReports")
                        .HasForeignKey("ReportedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FloodLink.Domain.Entities.Shelter", "Shelter")
                        .WithMany("Reports")
                        .HasForeignKey("ShelterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Reporter");

                    b.Navigation("Shelter");
                });

            modelBuilder.Entity("FloodLink.Domain.Entities.RouteEntity", b =>
                {
                    b.HasOne("FloodLink.Domain.Entities.WorkflowRun", "WorkflowRun")
                        .WithMany()
                        .HasForeignKey("WorkflowRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WorkflowRun");
                });

            modelBuilder.Entity("FloodLink.Domain.Entities.Shelter", b =>
                {
                    b.HasOne("FloodLink.Domain.Entities.User", "ContactVolunteer")
                        .WithMany("ContactShelters")
                        .HasForeignKey("ContactVolunteerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ContactVolunteer");
                });

            modelBuilder.Entity("FloodLink.Domain.Entities.TriagePlanEntity", b =>
                {
                    b.HasOne("FloodLink.Domain.Entities.WorkflowRun", "CreatedByAgentRun")
                        .WithMany()
                        .HasForeignKey("CreatedByAgentRunId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("CreatedByAgentRun");
                });

            modelBuilder.Entity("FloodLink.Domain.Entities.Depot", b =>
                {
                    b.Navigation("InventoryItems");
                });

            modelBuilder.Entity("FloodLink.Domain.Entities.Shelter", b =>
                {
                    b.Navigation("Reports");
                });

            modelBuilder.Entity("FloodLink.Domain.Entities.User", b =>
                {
                    b.Navigation("ContactShelters");

                    b.Navigation("SubmittedReports");
                });
#pragma warning restore 612, 618
        }
    }
}
