namespace FloodLink.Contracts.Agents;

/// <summary>
/// Represents the complete result produced by the logistics matching agent.
/// </summary>
public class MatchingResult
{
    /// <summary>
    /// Gets or sets the allocation proposals generated by the matching process.
    /// </summary>
    public List<AllocationProposalDto> Proposals { get; set; } = new();

    /// <summary>
    /// Gets or sets the resource needs that could not be completely fulfilled.
    /// </summary>
    public List<UnfulfillableNeed> UnfulfillableNeeds { get; set; } = new();
}

/// <summary>
/// Represents a resource need that could not be completely fulfilled.
/// </summary>
public class UnfulfillableNeed
{
    /// <summary>
    /// Gets or sets the shelter that requires the resource.
    /// </summary>
    public int ShelterId { get; set; }

    /// <summary>
    /// Gets or sets the name of the required item.
    /// </summary>
    public string ItemName { get; set; } = string.Empty;

    /// <summary>
    /// Gets or sets the originally requested quantity.
    /// </summary>
    public decimal RequestedQuantity { get; set; }

    /// <summary>
    /// Gets or sets the quantity that could not be fulfilled.
    /// </summary>
    public decimal UnfulfilledQuantity { get; set; }

    /// <summary>
    /// Gets or sets the reason why the need could not be fulfilled.
    /// </summary>
    public string Reason { get; set; } = string.Empty;
}