<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>FloodLink.Api</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\FloodLink.Infrastructure\FloodLink.Infrastructure.csproj" />
    <ProjectReference Include="..\FloodLink.Contracts\FloodLink.Contracts.csproj" />
    <ProjectReference Include="..\FloodLink.Domain\FloodLink.Domain.csproj" />
    <ProjectReference Include="..\FloodLink.Agents.Triage\FloodLink.Agents.Triage.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Swashbuckle.AspNetCore" />
  </ItemGroup>
</Project>
