// ── FloodLink AI — Placeholder Page ─────────────────────────────────────────
//
// Shown for pages not yet implemented (Dashboard, Incidents, Approvals, etc.).
// Keeps the shell functional while individual feature screens are being built.
// ─────────────────────────────────────────────────────────────────────────────

import { PageId } from '../nav';

const PAGE_LABELS: Record<PageId, string> = {
  dashboard: 'Dashboard',
  incidents: 'Incident Reports',
  inventory: 'Inventory',
  depots: 'Depots',
  approvals: 'Approvals Queue',
  routes: 'Routes',
  logs: 'Execution Logs',
};

const PAGE_DESCRIPTIONS: Partial<Record<PageId, string>> = {
  dashboard:  'Map-first overview of active incidents, resource status, and AI response plans.',
  incidents:  'Incoming field reports from volunteers — triaged and queued for AI processing.',
  approvals:  'Human review of AI-generated dispatch plans before activation.',
  routes:     'Route/ETA plans generated by the Route Agent, with map visualisation (Mapbox).',
  logs:       'AgentExecutionLog viewer — full audit trail of every AI agent action.',
};

export default function PlaceholderPage({ pageId }: { pageId: PageId }) {
  return (
    <div className="fl-page">
      <header className="fl-page-header">
        <div>
          <p className="fl-page-header__eyebrow">FloodLink AI</p>
          <h1 className="fl-page-header__title">{PAGE_LABELS[pageId]}</h1>
          {PAGE_DESCRIPTIONS[pageId] && (
            <p className="fl-page-header__subtitle">{PAGE_DESCRIPTIONS[pageId]}</p>
          )}
        </div>
      </header>

      <div className="fl-state-message" role="status">
        <p style={{ margin: '0 0 8px', fontWeight: 600 }}>Under construction</p>
        <p style={{ margin: 0, fontSize: 12 }}>
          This section is being built. Check{' '}
          <code style={{ fontFamily: 'var(--font-mono)', fontSize: 11 }}>CONTRIBUTING.md</code>
          {' '}for ownership and sprint assignments.
        </p>
      </div>
    </div>
  );
}
